#ifndef DEFINES_H
#define DEFINES_H

#define PRIMARY_PAYLOAD_LOCATION 0
#define SECONDARY_PAYLOAD_LOCATION 1

#define PRIMARY_CHIT_IDX 0
#define SECONDARY_CHIT_IDX 1
#define PRIMARY_MISS_IDX 0
#define SECONDARY_MISS_IDX 1

#endif
