#ifndef DEFINES_H
#define DEFINES_H

// Ray generation payload locations
#define PRIMARY_PAYLOAD_LOCATION 0
#define SECONDARY_PAYLOAD_LOCATION 1

// Shader locations
#define PRIMARY_CHIT_IDX 0
#define SECONDARY_CHIT_IDX 1
#define PRIMARY_MISS_IDX 0
#define SECONDARY_MISS_IDX 1

// Descriptor set locations
// Set 0
#define DESCRIPTOR_SET_0_NUM_BINDINGS 6
#define ACCELERATION_STRUCTURE_NV_BINDING_LOCATION 0
#define RESULT_IMAGE_BINDING_LOCATION 1
#define OCCLUSION_IMAGE_BINDING_LOCATION 2
#define CAMERA_BUFFER_BINDING_LOCATION 3
#define LIGHTS_BUFFER_BINDING_LOCATION 4
#define OTHER_DATA_BUFFER_BINDING_LOCATION 5

// Set 1
#define DESCRIPTOR_SET_1_NUM_BINDINGS 5
#define CUSTOM_ID_TO_ATTRIBUTE_ARRAY_INDEX_BUFFER_BINDING_LOCATION 0
#define PER_MESH_ATTRIBUTES_BINDING_LOCATION 1
#define PER_VERTEX_ATTRIBUTES_BINDING_LOCATION 2
#define DIFFUSE_TEXTURES_BINDING_LOCATION 3
#define SPECULAR_TEXTURES_BINDING_LOCATION 4

// Material types
#define MATTE_MATERIAL 1.0f
#define MIRROR_MATERIAL 2.0f
#define WATER_MATERIAL 4.0f
#define GLASS_MATERIAL 8.0f

// Shader-ONLY values
#define MAX_OCCLUSION_DIST 1.0f
#define POLYNONIAL_AO_ATTENUATION_Y_MAX 4.0f
#define POLYNOMIAL_AO_ATTENUATION_POWER 40
#define DEFAULT_OCCLUSION 0.0f

#endif
